inherit_from: .rubocop_todo.yml

require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
